# Generated by Django 5.1.5 on 2025-01-17 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='added_on',
            new_name='created_at',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_panel.employee'),
        ),
    ]
